name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Run tests & Build
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Clear pnpm cache
        run: pnpm cache clear

      - name: Show Node.js and npm versions
        run: |
          node --version
          npm --version
