name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install npm
      run: npm install

    - name: Install dependencies
      run: npm install --frozen-lockfile

    - name: Build project
      run: npm build

